require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lounge_memberships", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LoungeMembership. As you add validations to LoungeMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LoungeMembership.create! valid_attributes
      get lounge_memberships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lounge_membership = LoungeMembership.create! valid_attributes
      get lounge_membership_url(lounge_membership)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lounge_membership_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lounge_membership = LoungeMembership.create! valid_attributes
      get edit_lounge_membership_url(lounge_membership)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LoungeMembership" do
        expect {
          post lounge_memberships_url, params: { lounge_membership: valid_attributes }
        }.to change(LoungeMembership, :count).by(1)
      end

      it "redirects to the created lounge_membership" do
        post lounge_memberships_url, params: { lounge_membership: valid_attributes }
        expect(response).to redirect_to(lounge_membership_url(LoungeMembership.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LoungeMembership" do
        expect {
          post lounge_memberships_url, params: { lounge_membership: invalid_attributes }
        }.to change(LoungeMembership, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lounge_memberships_url, params: { lounge_membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lounge_membership" do
        lounge_membership = LoungeMembership.create! valid_attributes
        patch lounge_membership_url(lounge_membership), params: { lounge_membership: new_attributes }
        lounge_membership.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lounge_membership" do
        lounge_membership = LoungeMembership.create! valid_attributes
        patch lounge_membership_url(lounge_membership), params: { lounge_membership: new_attributes }
        lounge_membership.reload
        expect(response).to redirect_to(lounge_membership_url(lounge_membership))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lounge_membership = LoungeMembership.create! valid_attributes
        patch lounge_membership_url(lounge_membership), params: { lounge_membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lounge_membership" do
      lounge_membership = LoungeMembership.create! valid_attributes
      expect {
        delete lounge_membership_url(lounge_membership)
      }.to change(LoungeMembership, :count).by(-1)
    end

    it "redirects to the lounge_memberships list" do
      lounge_membership = LoungeMembership.create! valid_attributes
      delete lounge_membership_url(lounge_membership)
      expect(response).to redirect_to(lounge_memberships_url)
    end
  end
end
