require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/memberships", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Membership. As you add validations to Membership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Membership.create! valid_attributes
      get memberships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      membership = Membership.create! valid_attributes
      get membership_url(membership)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_membership_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      membership = Membership.create! valid_attributes
      get edit_membership_url(membership)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Membership" do
        expect {
          post memberships_url, params: { membership: valid_attributes }
        }.to change(Membership, :count).by(1)
      end

      it "redirects to the created membership" do
        post memberships_url, params: { membership: valid_attributes }
        expect(response).to redirect_to(membership_url(Membership.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Membership" do
        expect {
          post memberships_url, params: { membership: invalid_attributes }
        }.to change(Membership, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post memberships_url, params: { membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested membership" do
        membership = Membership.create! valid_attributes
        patch membership_url(membership), params: { membership: new_attributes }
        membership.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the membership" do
        membership = Membership.create! valid_attributes
        patch membership_url(membership), params: { membership: new_attributes }
        membership.reload
        expect(response).to redirect_to(membership_url(membership))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        membership = Membership.create! valid_attributes
        patch membership_url(membership), params: { membership: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested membership" do
      membership = Membership.create! valid_attributes
      expect {
        delete membership_url(membership)
      }.to change(Membership, :count).by(-1)
    end

    it "redirects to the memberships list" do
      membership = Membership.create! valid_attributes
      delete membership_url(membership)
      expect(response).to redirect_to(memberships_url)
    end
  end
end
