require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/special_offers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SpecialOffer. As you add validations to SpecialOffer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SpecialOffer.create! valid_attributes
      get special_offers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      special_offer = SpecialOffer.create! valid_attributes
      get special_offer_url(special_offer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_special_offer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      special_offer = SpecialOffer.create! valid_attributes
      get edit_special_offer_url(special_offer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SpecialOffer" do
        expect {
          post special_offers_url, params: { special_offer: valid_attributes }
        }.to change(SpecialOffer, :count).by(1)
      end

      it "redirects to the created special_offer" do
        post special_offers_url, params: { special_offer: valid_attributes }
        expect(response).to redirect_to(special_offer_url(SpecialOffer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SpecialOffer" do
        expect {
          post special_offers_url, params: { special_offer: invalid_attributes }
        }.to change(SpecialOffer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post special_offers_url, params: { special_offer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested special_offer" do
        special_offer = SpecialOffer.create! valid_attributes
        patch special_offer_url(special_offer), params: { special_offer: new_attributes }
        special_offer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the special_offer" do
        special_offer = SpecialOffer.create! valid_attributes
        patch special_offer_url(special_offer), params: { special_offer: new_attributes }
        special_offer.reload
        expect(response).to redirect_to(special_offer_url(special_offer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        special_offer = SpecialOffer.create! valid_attributes
        patch special_offer_url(special_offer), params: { special_offer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested special_offer" do
      special_offer = SpecialOffer.create! valid_attributes
      expect {
        delete special_offer_url(special_offer)
      }.to change(SpecialOffer, :count).by(-1)
    end

    it "redirects to the special_offers list" do
      special_offer = SpecialOffer.create! valid_attributes
      delete special_offer_url(special_offer)
      expect(response).to redirect_to(special_offers_url)
    end
  end
end
